website_serie:
    resource: "@WebsiteSerieBundle/Resources/config/routing.yml"
    prefix:   /

website_music:
    resource: "@WebsiteMusicBundle/Resources/config/routing.yml"
    prefix:   /

website_movies:
    resource: "@WebsiteMoviesBundle/Resources/config/routing.yml"
    prefix:   /

website_home:
    resource: "@WebsiteHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"