website_music_homepage:
    path:     /musics
    defaults: { _controller: WebsiteMusicBundle:Music:index }

website_music_getallmusics:
    path:     /musics-getall
    defaults: { _controller: WebsiteMusicBundle:Music:getAllMusics }
    options:
        expose: true

website_music_search:
    path:     /musics-search
    defaults: { _controller: WebsiteMusicBundle:Music:search }
    options:
        expose: true